# Defining kNN

Сделаем генерализованный слой для kNN-регрессии, опишем его в файле `knn.py`.

In [1]:
import numpy as np
import pandas as pd

from matplotlib import pyplot as plt
import seaborn as sns; sns.set_style()

import utils
import knn

%load_ext autoreload
%autoreload 2
%matplotlib inline

Теперь попробуем сделать что-нибудь простенькое с нашим kNN:

In [7]:
points = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
]).astype('float')

labels = np.array([
    [0],
    [1],
    [1],
    [2]
]).astype('float')

test = np.array([
    [.5, .5],
    [.0, .0],
    [.0, 1.],
    [1., 1.]
])

points, labels, test

(array([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]]),
 array([[0.],
        [1.],
        [1.],
        [2.]]),
 array([[0.5, 0.5],
        [0. , 0. ],
        [0. , 1. ],
        [1. , 1. ]]))

In [8]:
knn.knnRegression(window_parameter = 1).fit(points, labels).transform(test)

array([[0.],
       [0.],
       [1.],
       [2.]])

Ну вроде что-то получается.