# SMAPE

Немного вычислений градиента для SMAPE. Положим:

$$
y_i = f_i(x) = \sum_{j=0}^{m} w_j \cdot x_{ij} = w_j \cdot x_{ij} + C
$$

Тогда хотим найти:

$$
\begin{align}
&\frac{d}{dx} \cdot \frac{|y - f(x)|}{|y| + |f(x)|} = \\
&=\frac{f'(x) \left(\frac{-f(x) (y - f(x))^2}{|f(x)|} - (y - f(x)) |f(x)| + |y|)\right)}{|y - f(x)| (|f(x)| + |y|)^2} = \\
&=-f'(x) \cdot \left(\frac{\text{sign}(f(x)) \cdot |y - f(x)|}{(|y| + |f(x)|)^2} + \frac{\text{sign}(y - f(x))}{|y| + |f(x)|}\right)=\\
&=-f'(x) \cdot \frac{\text{sign}(f(x)) \cdot |y - f(x)| + \text{sign}(y - f(x)) \cdot (|y| + |f(x)|)}{(|y| + |f(x)|)^2}
\end{align}
$$

Отсюда можно видеть, что:

$$
\frac{dy_i}{w_j} = x_{ij} \cdot g(y_i, \hat{y_i})
$$

Отсюда:

$$
\frac{\delta y_i}{\delta w} = x_i \cdot g(y_i, \hat{y_i})
$$

Где:

$$
g(y_i, \hat{y_i}) = \frac{\text{sign}(\hat{y_i} - y_i) \cdot (|\hat{y_i}| + |y_i|) - \text{sign}(\hat{y_i}) \cdot |\hat{y_i} - y_i|}{(|\hat{y_i}| + |y_i|)^2}
$$

Проверим пример из условия таски с кф (добавив столбец bias):

In [1]:
import numpy as np

features = np.array([[2015, 1],
                     [2016, 1]])

labels = np.array([2045, 2076])

coefs = np.array([31, -60420])

predicted = np.dot(features, coefs)

labels, predicted

(array([2045, 2076]), array([2045, 2076]))

Наверное, на этом примере ничего проверить не удастся)

Попробуем второй:

In [2]:
features = np.array([[1, 1],
                     [1, 1],
                     [2, 1],
                     [2, 1]])

labels = np.array([0, 2, 2, 4])

coefs = np.array([1, 1])

predicted = np.dot(features, coefs)

labels, predicted

(array([0, 2, 2, 4]), array([2, 2, 3, 3]))

In [3]:
import smape

fi = smape.smape_grad_f(predicted, labels)

fi

array([ 0.        ,  0.        ,  0.16      , -0.16326531])

In [4]:
for i, row in enumerate(features):
    print(row * fi[i])

[0. 0.]
[0. 0.]
[0.32 0.16]
[-0.32653061 -0.16326531]
