# Точное решение

Рассмотрим метод точного решения задачи линейной регрессии при помощи MSE (и MSE + ridge):

$$
L(\theta) = ||F\theta - y||^2 + \tau ||\theta||^2
$$

По умолчанию $\tau=0$, то есть ridge-регуляризация отключена. Тогда:

$$
\theta^* = \left(F^TF + \tau I_m\right)^{-1} F^T y
$$

Будем использовать псевдообратную матрицу и рассчитаем таким образом оптимальное значение.

In [1]:
from exact import ExactRegressor as ExReg
from sklearn.linear_model import LinearRegression as LinReg

er = ExReg()
lr = LinReg()

In [2]:
import numpy as np

features = np.array([[2],
                     [3],
                     [5]])

labels = np.array([0, 1, 2])

In [3]:
er.fit(features, labels).predict(features)

array([0.14285714, 0.78571429, 2.07142857])

In [4]:
lr.fit(features, labels).predict(features)

array([0.14285714, 0.78571429, 2.07142857])

Как можно видеть, наш регрессор ведёт себя точно так же, как и sklearn-овский, что можно считать успехом. Попробуем добавить параметры:

In [5]:
eri = ExReg(fit_intercept=False)
lri = LinReg(fit_intercept=False)

In [6]:
eri.fit(features, labels).predict(features)

array([0.68421053, 1.02631579, 1.71052632])

In [7]:
lri.fit(features, labels).predict(features)

array([0.68421053, 1.02631579, 1.71052632])

Аналогично.

Теперь посмотрим, как изменится решение нашего классификатора, если ему передать параметр регуляризации:

In [8]:
err = ExReg(ridge_coef = 0.1)

err.fit(features, labels).predict(features)

array([0.1863354 , 0.80745342, 2.04968944])

Ну, что-то точно происходит.